In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

## Training Set

In [2]:
train_datagen = ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)
training_set = train_datagen.flow_from_directory('seg_train/',target_size=(64,64),batch_size= 64,class_mode= 'categorical')

Found 14034 images belonging to 6 classes.


## Test Set

In [3]:
test_datagen = ImageDataGenerator(rescale=1./255)
test_set = test_datagen.flow_from_directory('seg_test/',target_size=(64,64),batch_size= 64,class_mode='categorical')

Found 3000 images belonging to 6 classes.


## Building the CNN

In [4]:
cnn = tf.keras.models.Sequential()

In [5]:
cnn.add(tf.keras.layers.Conv2D(filters=32,kernel_size=5,activation='relu',input_shape = [64,64,3]))

### Pooling

In [6]:
cnn.add(tf.keras.layers.MaxPool2D(pool_size = 2,strides=2))

### Second Convolutional Layer

In [7]:
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=5, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [8]:
cnn.add(tf.keras.layers.Flatten())

### Full Connection

In [9]:
cnn.add(tf.keras.layers.Dense(units=128,activation='relu'))

### Output Layers

In [10]:
cnn.add(tf.keras.layers.Dense(units=6,activation='softmax'))

# > Training the CNNs

In [11]:
cnn.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [12]:
cnn.fit(x=training_set,validation_data=test_set,epochs=25)

Epoch 1/25
220/220 [==============================] - 135s 615ms/step - loss: 1.0974 - accuracy: 0.5715 - val_loss: 0.8848 - val_accuracy: 0.6650
Epoch 2/25
220/220 [==============================] - 47s 212ms/step - loss: 0.8692 - accuracy: 0.6692 - val_loss: 0.7935 - val_accuracy: 0.7123
Epoch 3/25
220/220 [==============================] - 47s 213ms/step - loss: 0.7836 - accuracy: 0.7084 - val_loss: 0.7558 - val_accuracy: 0.7347
Epoch 4/25
220/220 [==============================] - 47s 212ms/step - loss: 0.7115 - accuracy: 0.7350 - val_loss: 0.6929 - val_accuracy: 0.7607
Epoch 5/25
220/220 [==============================] - 47s 212ms/step - loss: 0.6641 - accuracy: 0.7550 - val_loss: 0.6877 - val_accuracy: 0.7677
Epoch 6/25
220/220 [==============================] - 47s 215ms/step - loss: 0.6360 - accuracy: 0.7641 - val_loss: 0.6302 - val_accuracy: 0.7840
Epoch 7/25
220/220 [==============================] - 47s 212ms/step - loss: 0.5963 - accuracy: 0.7830 - val_loss: 0.6350 - val_a

In [14]:
cnn.save("cnn.h5")

In [13]:
from tensorflow.keras.preprocessing import image

In [14]:
test_image = image.load_img("pred/51.jpg",target_size = (64,64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image,axis = 0)
test_image.shape

(1, 64, 64, 3)

In [15]:
result = cnn.predict(test_image)

In [16]:
training_set.class_indices

{'buildings': 0,
 'forest': 1,
 'glacier': 2,
 'mountain': 3,
 'sea': 4,
 'street': 5}

In [17]:
print(result) #171

[[0. 0. 1. 0. 0. 0.]]


In [18]:
print(result) #103

[[0. 0. 1. 0. 0. 0.]]


In [19]:
print(result) #51

[[0. 0. 1. 0. 0. 0.]]


In [20]:
img = image.load_img("pred/51.jpg")
img = image.img_to_array(img)